---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian11
    image: geerlingguy/docker-debian11-ansible
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: debian10
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: el9
    image: geerlingguy/docker-rockylinux9-ansible
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: el8
    image: geerlingguy/docker-rockylinux8-ansible
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"

  - name: el7
    image: geerlingguy/docker-centos7-ansible
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"


provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
